//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LipsumGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LipsumTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LipsumTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LipsumGenerator.Properties.LipsumTable", typeof(LipsumTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kivül belõl
        ///leselkedõ halál elõl
        ///mint lukba megriadt egérke
        ///
        ///amíg hevülsz
        ///az asszonyhoz úgy menekülsz
        ///hogy óvjon karja öle térde
        ///
        ///nemcsak a lágy
        ///meleg öl csal nemcsak a vágy
        ///de odataszít a muszáj is
        ///
        ///ezért ölel
        ///minden ami asszonyra lel
        ///míg el nem fehérül a száj is
        ///
        ///kettõs teher
        ///s kettõs kincs hogy szeretni kell
        ///ki szeret s párra nem találhat
        ///
        ///oly hontalan
        ///mint amilyen gyámoltalan
        ///a szükségét végzõ vadállat
        ///
        ///nincsen egyéb
        ///menedékünk a kés hegyét
        ///bár anyádnak szegezd te bátor
        ///
        ///és l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Attila {
            get {
                return ResourceManager.GetString("Attila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comme je descendais des fleuves impassibles
        ///je ne me sentis plus guidé par les haleurs
        ///des peaux-rouges criards les avaient pris pour cibles
        ///les ayant cloués nus aux poteaux de couleurs
        ///
        ///j&apos;étais insoucieux de tous les équipages
        ///porteur de blés flamands ou de cotons anglais
        ///quand avec mes haleurs ont fini ces tapages
        ///les fleuves m&apos;ont laissé descendre ou je voulais
        ///
        ///dans les clapotements furieux des marées
        ///moi l&apos;autre hiver plus sourd que les cerveaux d&apos;enfants
        ///je courus  et les péninsules démarr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Baudelaire {
            get {
                return ResourceManager.GetString("Baudelaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam nonumy
        ///eirmod tempor invidunt ut labore et dolore magna aliquyam erat sed diam
        ///voluptua at vero eos et accusam et justo duo dolores et ea rebum stet clita
        ///kasd gubergren no sea takimata sanctus est lorem ipsum dolor sit amet lorem
        ///ipsum dolor sit amet consetetur sadipscing elitr sed diam nonumy eirmod
        ///tempor invidunt ut labore et dolore magna aliquyam erat sed diam voluptua at
        ///vero eos et accusam et justo duo dolores et ea rebum stet clit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cicero {
            get {
                return ResourceManager.GetString("Cicero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ihr naht euch wieder schwankende gestalten
        ///die früh sich einst dem trüben blick gezeigt
        ///versuch ich wohl euch diesmal festzuhalten
        ///fühl ich mein herz noch jenem wahn geneigt
        ///ihr drängt euch zu  nun gut so mögt ihr walten
        ///wie ihr aus dunst und nebel um mich steigt
        ///mein busen fühlt sich jugendlich erschüttert
        ///vom zauberhauch der euren zug umwittert
        ///
        ///ihr bringt mit euch die bilder froher tage
        ///und manche liebe schatten steigen auf
        ///gleich einer alten halbverklungnen sage
        ///kommt erste lieb und freundsc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Faust {
            get {
                return ResourceManager.GetString("Faust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es treibt dich fort von ort zu ort
        ///du weißt nicht mal warum
        ///im winde klingt ein sanftes wort
        ///schaust dich verwundert um
        ///
        ///die liebe die dahinten blieb
        ///sie ruft dich sanft zurück
        ///o komm zurück ich hab dich lieb
        ///du bist mein einz&apos;ges glück
        ///
        ///doch weiter weiter sonder rast
        ///du darfst nicht stillestehn
        ///was du so sehr geliebet hast
        ///sollst du nicht wiedersehn
        ///
        ///du bist ja heut so grambefangen
        ///wie ich dich lange nicht geschaut
        ///es perlet still von deinen wangen
        ///und deine seufzer werden laue
        ///
        ///denkst  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fremde {
            get {
                return ResourceManager.GetString("Fremde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura, ché la diritta via era smarrita.
        ///Ahi quanto a dir qual era è cosa dura esta selva selvaggia e aspra e forte che nel pensier rinova la paura!
        ///Tant’ è amara che poco è più morte; ma per trattar del ben ch’i’ vi trovai, dirò de l’altre cose ch’i’ v’ho scorte.
        ///Io non so ben ridir com’ i’ v’intrai, tant’ era pien di sonno a quel punto che la verace via abbandonai.
        ///Ma poi ch’i’ fui al piè d’un colle giunto, là dove terminava quella valle ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inferno {
            get {
                return ResourceManager.GetString("Inferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi naskigxis en jorko anglujo je marto kiu estas la
        ///sesjarrego de la regxo karolo la unua infane mi sentadis grandan
        ///deziron por pasigi mian vivon sur la maro kaj pliagxante la deziro
        ///plifortigxis gxis fine mi forlasis mian lernejon kaj hejmon kaj
        ///piede mi trovis mian vojon al hull kie mi baldaux trovis okupadon sur
        ///sxipo
        ///
        ///post kiam ni velveturis kelke da tagoj okazis ventego kaj kvinanokte
        ///la sxipo enfendigxis cxiuj al la pumpiloj rapidis la sxipon ni sentis
        ///gxemi en cxiuj siaj tabuloj kaj gxian t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KrusoEsperanto {
            get {
                return ResourceManager.GetString("KrusoEsperanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contemplons ce trésor de grâces florentines
        ///dans l&apos;ondulation de ce corps musculeux
        ///l&apos;elégance et la force abondent soeurs divines
        ///cette femme morceau vraiment miraculeux
        ///divinement robuste adorablement mince
        ///est faite pour trôner sur des lits somptueux
        ///et charmer les loisirs d&apos;un pontife ou d&apos;un prince
        ///
        ///aussi vois ce souris fin et voluptueux
        ///ou la fatuité promene son extase
        ///ce long regard sournois langoureux et moqueur
        ///ce visage mignard tout encadré de gaze
        ///dont chaque trait nous dit avec un ai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeMasque {
            get {
                return ResourceManager.GetString("LeMasque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oh thou in hellas deemed of heavenly birth
        ///muse formed or fabled at the minstrels will
        ///since shamed full oft by later lyres on earth
        ///mine dares not call thee from thy sacred hill
        ///yet there ive wandered by thy vaunted rill
        ///yes sighed oer delphis longdeserted shrine
        ///where save that feeble fountain all is still
        ///nor mote my shell awake the weary nine
        ///to grace so plain a talethis lowly lay of mine
        ///
        ///whilome in albions isle there dwelt a youth
        ///who ne in virtues ways did take delight
        ///but spent his days  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LordByron {
            get {
                return ResourceManager.GetString("LordByron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me quedo con el transparente hombrecillo
        ///que come los huevos de la golondrina
        ///me quedo con el nino desnudo
        ///que pisotean los borrachos de brooklyn
        ///con las criaturas mudas que pasan bajo los arcos
        ///con el arroyo de venas ansioso de abrir sus manecitas
        ///
        ///tierra tan sólo tierra
        ///tierra para los manteles estremecidos
        ///para la pupila viciosa de nube
        ///para las heridas recientes y el húmedo pensamiento
        ///tierra para todo lo que huye de la tierra
        ///
        ///no es la ceniza en vilo de las cosas quemadas
        ///ni los muertos q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Luna {
            get {
                return ResourceManager.GetString("Luna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convenevole cosa e carissime donne che ciascheduna cosa la quale l&apos;uomo fa
        ///dallo ammirabile e santo nome di colui il quale di tutte fu facitore le dea
        ///principio per che dovendo io al vostro novellare sí come primo dare
        ///cominciamento intendo da una delle sue maravigliose cose incominciare accio
        ///che quella udita la nostra speranza in lui sí come in cosa impermutabile si
        ///fermi e sempre sia da noi il suo nome lodato manifesta cosa e che sí come le
        ///cose temporali tutte sono transitorie e mortali cosí in sé [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NovellaPrima {
            get {
                return ResourceManager.GetString("NovellaPrima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once upon a midnight dreary while i pondered weak and weary
        ///over many a quaint and curious volume of forgotten lore
        ///while i nodded nearly napping suddenly there came a tapping
        ///as of some one gently rapping rapping at my chamber door
        ///tis some visiter i muttered tapping at my chamber door
        ///only this and nothing more
        ///
        ///ah distinctly i remember it was in the bleak december
        ///and each separate dying ember wrought its ghost upon the floor
        ///eagerly i wished the morrow vainly i had sought to borrow
        ///from my boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Poe {
            get {
                return ResourceManager.GetString("Poe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volek syrolm thudothlon syrolmol sepedyk buol ozuk epedek walasth vylagumtul
        ///sydou fyodumtul ezes urumemtuul o en eses urodum eggen yg fyodum syrou aniath
        ///thekunched buabeleul kyniuhhad scemem kunuel arad en iunhum buol farad the
        ///werud hullothya en iunhum olelothya vylag uilaga viragnac uiraga keseruen
        ///kynzathul uos scegegkel werethul vh nequem en fyon ezes mezuul scegenul
        ///scepsegud wirud hioll wyzeul syrolmom fuhazatum therthetyk kyul en iumhumnok
        ///bel bua qui sumha nym kyul hyul wegh halal engumet eg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Siralom {
            get {
                return ResourceManager.GetString("Siralom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to han kom som ett yrväder en aprilafton och hade
        ///ett höganäskrus i en svångrem om halsen clara
        ///och lotten voro inne med skötekan att hämta
        ///honom på dalarö brygga men det dröjde evigheter
        ///innan de kommo i båt de skulle till handelsman
        ///och ha en tunna tjära och på abeteket och hämta
        ///gråsalva åt grisen och så skulle de på posten och
        ///få ett frimärke och så skulle de ner till fia lövström
        ///i kroken och låna tuppen mot ett halvpund
        ///småtärna till notbygget och sist hade de hamnat på
        ///gästgivaregården där car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strindberg {
            get {
                return ResourceManager.GetString("Strindberg", resourceCulture);
            }
        }
    }
}
